# Generated by Django 4.1.5 on 2023-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(db_column='name', max_length=30)),
                ('column2', models.CharField(db_column='password', max_length=10)),
            ],
            options={
                'db_table': 'mytable',
                'managed': False,
            },
        ),
    ]
