# Generated by Django 4.1.5 on 2023-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0002_students_delete_mytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=264)),
                ('roll_no', models.CharField(db_column='roll_no', max_length=264)),
                ('password', models.CharField(db_column='password', max_length=264)),
                ('mobile', models.IntegerField(db_column='mobile_no', max_length=10)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('dob', models.DateField(db_column='dob')),
                ('tenth', models.IntegerField(db_column='tenth_mark')),
                ('twelve', models.IntegerField(db_column='twelth_mark')),
                ('twelth_cutoff', models.IntegerField(db_column='twelth_cutoff')),
            ],
            options={
                'db_table': 'student_signup',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
