# Generated by Django 4.1.5 on 2023-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0003_student_sign_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_column='staff_id', max_length=30)),
                ('staff_name', models.CharField(db_column='staff_name', max_length=30)),
                ('staff_email', models.EmailField(db_column='staff_email', max_length=254)),
                ('staff_password', models.CharField(db_column='staff_password', max_length=15)),
            ],
            options={
                'db_table': 'staff_sigup',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student_sign',
            options={},
        ),
    ]
