# Generated by Django 4.1.5 on 2023-03-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0004_staff_sign_alter_student_sign_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff_sign',
        ),
        migrations.AlterModelOptions(
            name='student_sign',
            options={'managed': False},
        ),
    ]
