# Generated by Django 4.1.5 on 2023-03-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0005_delete_staff_sign_alter_student_sign_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_sign',
            table='staff_signup',
        ),
    ]
