# Generated by Django 4.1.5 on 2023-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0006_alter_student_sign_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(db_column='staffid', max_length=264)),
                ('staffname', models.CharField(db_column='staffname', max_length=264)),
                ('staffemail', models.EmailField(db_column='staffmail', max_length=254)),
                ('staffconfirm', models.CharField(db_column='staffconfirm', max_length=264)),
            ],
            options={
                'db_table': 'staff_signup',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='student_sign',
            table='student_signup',
        ),
    ]
