# Generated by Django 4.1.5 on 2023-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0007_staff_sign_alter_student_sign_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff_sign',
            table='staff_sign',
        ),
    ]
