# Generated by Django 4.1.5 on 2023-03-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0010_photo_p_alter_student_sign_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_sign',
            options={'managed': False},
        ),
    ]
