# Generated by Django 4.1.5 on 2023-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0011_alter_student_sign_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_upload',
            fields=[
                ('ids', models.IntegerField(db_column='ids', primary_key=True, serialize=False)),
                ('event_type', models.TextField(db_column='event_type')),
                ('event_name', models.TextField(db_column='event_name')),
                ('event_title', models.TextField(db_column='event_title')),
                ('event_host', models.TextField(db_column='event_host')),
                ('from_date', models.DateField(db_column='from_date')),
                ('to_date', models.DateField(db_column='to_date')),
                ('files', models.BinaryField(db_column='file_data')),
                ('file_name', models.TextField(db_column='file_name')),
            ],
            options={
                'db_table': 'staff_uploads',
                'managed': False,
            },
        ),
    ]
