# Generated by Django 4.1.5 on 2023-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0012_staff_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_up',
            fields=[
                ('staff_id', models.CharField(db_column='staff_id', max_length=264)),
                ('ids', models.IntegerField(db_column='ids', primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='file_name', max_length=264)),
                ('file', models.BinaryField(db_column='file')),
                ('from_date', models.DateField(db_column='from_date')),
                ('to_date', models.DateField(db_column='to_date')),
                ('journal', models.CharField(db_column='journal', max_length=264)),
                ('title', models.CharField(db_column='title', max_length=264)),
                ('host', models.CharField(db_column='host', max_length=264)),
            ],
            options={
                'db_table': 'staff_files',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='staff_upload',
        ),
        migrations.AlterModelTable(
            name='photo_p',
            table='student_files',
        ),
    ]
