# Generated by Django 4.1.5 on 2023-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollege', '0013_staff_up_delete_staff_upload_alter_photo_p_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sem', models.CharField(db_column='sem', max_length=264)),
                ('subject', models.CharField(db_column='subject', max_length=264)),
                ('mark1', models.IntegerField(db_column='internal1')),
                ('mark2', models.IntegerField(db_column='internal2')),
                ('mark3', models.IntegerField(db_column='internal3')),
            ],
            options={
                'db_table': 'mark',
                'managed': False,
            },
        ),
    ]
