from django.urls import path
from django.urls import include
from dcollege import urls
from dcollege import views
urlpatterns = [
    path('',views.index,name="index"),
    path('stu/',views.sign_for_stu,name="stu"),
    path('hel/',views.index,name="index"),
    path('staff_reg/hel/',views.index,name="index"),
    path('sucess/',views.student_signs,name="new"),
    path('staffsuccess/',views.staff,name="new"),
    path('my_view/',views.index2,name="my_view"),
    path('Button.html/Button.html',views.index3,name='Button.html'),
    path('upload/',views.photo1,name='upload'),
    path('d/',views.gets,name='d'),
    path('Button.html/ll.html/', views.display_data, name='Button/ll'),
    path('getfile/', views.get_file, name='getfile'),
    path('all_files/', views.all_file, name='all_files'),
    path('staff_login/', views.staff_log, name='staff_login'),
    path('staff_re/', views.staff_red, name='staff_re'),
    path('staff_reg/hel/staff_re/', views.staff_red, name='staff_re'),
    path('staff_ups/', views.staff_ups, name='staff_ups'),
    path('staff_download/', views.staff_download, name='staff_download'),
    path('student_cert/', views.student_view, name='student_cert'),
    path('staff_re/student_red/', views.student_red, name='staff_re/student_red'),
    path('staff_re/student_download/', views.student_download, name='staff_re/student_download'),
    path('logout/staff_re/student_download', views.student_download, name='staff_re/student_download'),
    path('student_download/', views.download_by, name='student_download'),
    path('Button.html/',views.index3,name='Button.html'),
    path('logouts/Button.html',views.index3,name='Button.html'),
    path('logout/',views.index3,name='logout'),
    path('logout/Button.html',views.index3,name='logout/Button.html'),
    path('logout/ll.html/', views.display_data, name='Button/ll'),
    path('logouts/', views.staff_logout, name='logouts'),
    path('logouts/staff_re', views.staff_red, name='logouts'),
    path('logout/staff_re/', views.staff_red, name='logout/staff_re'),
    path('logouts/student_download', views.student_download, name='logouts/student_download'),
    path('staff_reg/', views.staff_reg, name='staff_reg'), 
    path('Button.html/staff_re/', views.staff_red, name='staff_reg'), 
    path('save_assess/',views.save_ass,name="save_assess"),
    path('save_int/',views.saveinter,name="save_int"),
    path('save_unit/',views.saveunit,name="save_unit"),
    path('stub/',views.tab,name='stub'),
    path('prev/',views.prevs,name='prev'),
    path('prevss/',views.prevsion,name='prevss'),
    path('prevs1/',views.prevsion1,name='prevs1'),
    path('stub/dis_tab.html',views.tab1,name='stub/dis_tab.html'),
    
]